app/controllers/toppage_controller.rb

自動デプロイのテストのためコミットします

---

app/views/shared/_side_bar.html.erb

ワードポイントの数値を変更
AWS側に、自動でデプロイが行われるかを確認する必要があるため

自動デプロイのテスト

---

app/controllers/words_controller.rb
app/javascript/copy_clipboard.js

Beforeアクションの処理をコントローラのアクション内にインライン展開した
Beforeアクションの処理が正しく動作していない可能性があったため

調査：ワードポイントがEC2で動作しないため

---

app/controllers/concerns/point_method.rb
app/controllers/words_controller.rb

正しく反映されていなかった可能性があるため、再度デプロイするためにコミット
このMergeよりひとつ前のMergeで、point_method.rbの@word_point = '0' →@word_point = '未登録'としたが、それが影響したとは考えにくい

EC2での挙動に変化が見られた

---

app/assets/stylesheets/exchanged_word/index.css
app/assets/stylesheets/shared/header.css
app/assets/stylesheets/shared/main.css
app/assets/stylesheets/word/index.css
app/controllers/concerns/point_method.rb
app/views/exchanged_words/index.html.erb
app/views/exchanged_words/new.html.erb
app/views/shared/_header.html.erb
app/views/shared/_side_bar.html.erb
app/views/toppage/index.html.erb
app/views/words/index.html.erb
app/views/words/new.html.erb

掲示板を設置、ヘッダーとサイドバーのデザインやリンクを修正
MTGにて、デモンストレーションを行うため、見た目などを変更

リファクタリング-デザイン

---

spec/factories/exchanged_words.rb
spec/factories/word_points.rb
spec/models/word_point_spec.rb

ワードポイントに関する単体テストコードを追加
バリデーション時の動作を確認する必要があるから

単体テストコード：ワードポイント

---

app/controllers/exchanged_words_controller.rb

ワード交換のためのアルゴリズムを作成
実現したいことがActiveRecordで実現できなかったため、アルゴリズムを組み、対応する必要があったため。

ワード交換のためのアルゴリズム作成

---

app/models/good_reputation.rb
spec/factories/good_reputations.rb
spec/models/good_reputation_spec.rb

評価テーブルに関する単体テストコード追加
単体テストコードを実行する必要があるため

単体テストコード：評価テーブル

---

app/views/manuals/index.html.erb

操作マニュアルの動画を3つに変更。
利用するユーザー（企業担当者）が操作方法を理解できるようにする必要があるため

操作マニュアルを変更、追加

---

Gemfile
Gemfile.lock
app/assets/stylesheets/user/registration.css
app/controllers/concerns/error_message_flash.rb
app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/views/devise/registrations/new.html.erb
app/views/toppage/index.html.erb
config/initializers/recaptcha.rb
config/routes.rb

reCAPTCHAをユーザー新規登録画面へ追加
不正な登録(スパム)を防ぐため

reCAPTCHAを導入（要リファクタリングが必要）

---

app/assets/stylesheets/shared/main.css
app/javascript/mouse_over.js
app/views/about/index.html.erb
app/views/devise/registrations/edit.html.erb
app/views/exchanged_words/index.html.erb
app/views/exchanged_words/new.html.erb
app/views/exchanged_words/show.html.erb
app/views/manuals/index.html.erb
app/views/profiles/index.html.erb
app/views/toppage/index.html.erb
app/views/words/edit.html.erb
app/views/words/index.html.erb
app/views/words/new.html.erb

各種ページにヘッダー、サイドバーを追加
ログインページ、ユーザー新規登録ページ以外のページに、ヘッダーやサイドバーを配置しておく必要があるため
一部ページで、ヘッダーまたはサイドバーを出した場合、文字が一番上に表示される問題が発生中。
原因は調査中で、おそらくヘッダーやサイドバーでposition: relativeを使用していることが原因と考えている。

Webレスポンシブ対応(ヘッダー、サイドバーの修正)

---

app/assets/stylesheets/shared/header.css
app/assets/stylesheets/shared/main.css
app/assets/stylesheets/shared/sidebar.css
app/views/shared/_header.html.erb

- ヘッダーボタンおよびサイドバーボタンを最上部から最下部へ
- ヘッダーのボタンの配置を修正
- サイドバーのボタンの配置を修正
ユーザーがスマホで操作がしやすいように、デザイン設計をする必要があったため

Webレスポンシブ対応（ヘッダーおよびサイドバーのデザイン修正）

---

app/assets/stylesheets/about/index.css
app/assets/stylesheets/manual/index.css
app/assets/stylesheets/profile/index.css
app/assets/stylesheets/shared/main.css
app/assets/stylesheets/user/edit.css
app/views/manuals/index.html.erb

ワードのページ以外の各種ページをスマホ向けにデザイン
スマホを使用した場合、デザインが崩れてしまうため
また実機での動作確認のため、ワード以外のページをPush(ワードページは非常に複雑なため)

Webレスポンシブデザイン対応(ワードのページ以外の各種ページ修正)

---

app/assets/stylesheets/exchanged_word/index.css
app/assets/stylesheets/shared/error_messages.css
app/assets/stylesheets/word/index.css

各種ページを修正（ログイン、ユーザー新規登録画面以外）
スマホでの操作が行えるようにする必要があるため

Webレスポンシブデザイン対応

---

app/assets/stylesheets/shared/main.css
app/assets/stylesheets/user/edit.css
app/assets/stylesheets/user/login.css
app/assets/stylesheets/user/registration.css
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

スマホで使用した場合に発生していた各種細かな問題を修正し、実装
実機導入後に、発覚した問題を修正しなければ、本番稼働時にユーザービリティに影響を及ぼすため

Webレスポンシブデザイン対応（細かな部分修正）

---

config/environments/development.rb

SSL化に向けて設定

---

app/assets/javascript/dfp_control.js
app/assets/stylesheets/devicefingerprinting.scss
app/assets/stylesheets/devicefingerprinting/index.css
app/controllers/devicefingerprinting_controller.rb
app/helpers/devicefingerprinting_helper.rb
app/javascript/mouse_over.js
app/views/devicefingerprinting/index.html.erb
app/views/shared/_side_bar.html.erb
config/initializers/assets.rb
config/routes.rb
spec/helpers/devicefingerprinting_helper_spec.rb
spec/requests/devicefingerprinting_spec.rb

Device Finger Printingのページを実装
ポートフォリオの作品として、掲載したかったため

Device finger printing実装

---

app/views/manuals/index.html.erb

注意事項の動画を削除
新しいマニュアル動画へ差し替え
アプリのバージョンアップに伴い、動画を差し替える方針になったため

マニュアルページ更新

---

app/assets/stylesheets/application.css
app/assets/stylesheets/typing/index.css
app/views/typing/index.html.erb

タイピングページのデザインを一新
スマホで操作した場合、文字が重複する箇所があったため、対応

タイピングページデザイン修正

---

app/assets/javascript/typing.js

コード全体をリファクタリング（状態遷移ごとに、DOM操作などできるよう整理）
タイマーの処理を見直し、修正
コードが見にくかったため、全体をリファクタリングする必要があったため
タイマーの停止について、誤った理解があったため、必要なコードを追記し、正しくタイマーが止まるように修正

Javascriptの処理を見直し

---

app/assets/javascript/typing.js
app/assets/stylesheets/typing/index.css
app/views/typing/index.html.erb

ゲーム中に流れるBGMを追加
操作説明等のテキストを追加
ゲームとしての緊迫感を出したかったため
日本語入力をしないように注意したり、必要な上をを明記しておきたかったため

Bgm追加 & 操作説明追加

---

app/assets/javascript/typing.js

英語文字の置き換え処理を実装
（英語文章を取得してきた後、置き替える）
取得してきた英語文章の中に、入力しても判定できない文字があったため。

英語文字の置き換え処理実装
